version: '3.8'
services:
  victim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ctf-sql-injection-login-bypass-victim
    hostname: victim
    networks:
      ctf-network:
        ipv4_address: 172.22.194.10
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-sql-injection-login-bypass-attacker
    hostname: attacker
    networks:
      ctf-network:
        ipv4_address: 172.22.194.100
networks:
  ctf-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.194.0/24
          gateway: 172.22.194.1
