version: '3.8'
services:
  victim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ctf-sql-injection-login-bypass-victim
    hostname: victim
    ports:
      - '8080:8080'
    networks:
      - ctf-network
  attacker:
    image: kasmweb/kali-rolling-desktop:1.15.0
    container_name: ctf-sql-injection-login-bypass-attacker
    hostname: attacker
    ports:
      - '6901:6901'
    networks:
      - ctf-network
    shm_size: '512m'
    environment:
      - VNC_PW=password
      - KASM_PORT=6901
networks:
  ctf-network:
    driver: bridge
