services:
  ftp-server:
    build:
      context: ./ftp-server
      dockerfile: Dockerfile
    container_name: ctf-network-discovery-multi-target-ftp-server
    networks:
      ctf-network-discovery-multi-target-net:
        ipv4_address: 172.24.193.53
    restart: unless-stopped
  web-server:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    container_name: ctf-network-discovery-multi-target-web-server
    networks:
      ctf-network-discovery-multi-target-net:
        ipv4_address: 172.24.193.104
    restart: unless-stopped
  database-server:
    build:
      context: ./database-server
      dockerfile: Dockerfile
    container_name: ctf-network-discovery-multi-target-database-server
    networks:
      ctf-network-discovery-multi-target-net:
        ipv4_address: 172.24.193.36
    restart: unless-stopped
  file-server:
    build:
      context: ./file-server
      dockerfile: Dockerfile
    container_name: ctf-network-discovery-multi-target-file-server
    networks:
      ctf-network-discovery-multi-target-net:
        ipv4_address: 172.24.193.136
    restart: unless-stopped
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: ctf-network-discovery-multi-target-attacker
    networks:
      ctf-network-discovery-multi-target-net:
        ipv4_address: 172.24.193.3
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
networks:
  ctf-network-discovery-multi-target-net:
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.24.193.0/24
          gateway: 172.24.193.1
