services:
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: ctf-network-discovery-multi-target-attacker
    networks:
      ctf-network-discovery-multi-target-net:
        ipv4_address: 172.25.145.3
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
  web-server:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    container_name: ctf-network-discovery-multi-target-web-server
    networks:
      ctf-network-discovery-multi-target-net:
        ipv4_address: 172.25.145.185
    restart: unless-stopped
  ftp-server:
    build:
      context: ./ftp-server
      dockerfile: Dockerfile
    container_name: ctf-network-discovery-multi-target-ftp-server
    networks:
      ctf-network-discovery-multi-target-net:
        ipv4_address: 172.25.145.136
    restart: unless-stopped
  smb-server:
    build:
      context: ./smb-server
      dockerfile: Dockerfile
    container_name: ctf-network-discovery-multi-target-smb-server
    networks:
      ctf-network-discovery-multi-target-net:
        ipv4_address: 172.25.145.177
    restart: unless-stopped
  database-server:
    build:
      context: ./database-server
      dockerfile: Dockerfile
    container_name: ctf-network-discovery-multi-target-database-server
    networks:
      ctf-network-discovery-multi-target-net:
        ipv4_address: 172.25.145.128
    restart: unless-stopped
networks:
  ctf-network-discovery-multi-target-net:
    name: ctf-network-discovery-multi-target-net
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.25.145.0/24
          gateway: 172.25.145.1
