services:
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: ctf-network-discovery-multi-target-attacker
    networks:
      ctf-network-discovery-multi-target-net:
        ipv4_address: 172.25.145.3
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
  victim1:
    build:
      context: ./victim1
      dockerfile: Dockerfile
    container_name: ctf-network-discovery-multi-target-victim1
    networks:
      ctf-network-discovery-multi-target-net:
        ipv4_address: 172.25.145.121
    restart: unless-stopped
  victim2:
    build:
      context: ./victim2
      dockerfile: Dockerfile
    container_name: ctf-network-discovery-multi-target-victim2
    networks:
      ctf-network-discovery-multi-target-net:
        ipv4_address: 172.25.145.160
    restart: unless-stopped
  victim3:
    build:
      context: ./victim3
      dockerfile: Dockerfile
    container_name: ctf-network-discovery-multi-target-victim3
    networks:
      ctf-network-discovery-multi-target-net:
        ipv4_address: 172.25.145.120
    restart: unless-stopped
networks:
  ctf-network-discovery-multi-target-net:
    name: ctf-network-discovery-multi-target-net
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.25.145.0/24
          gateway: 172.25.145.1
