services:
  ctf-operation-silent-transfer-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-operation-silent-transfer-attacker
    hostname: attacker
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "operation-silent-transfer"
    networks:
      ctf-operation-silent-transfer-net:
        ipv4_address: 172.23.195.3
      ctf-instances-network:
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true

  ctf-operation-silent-transfer-ftp-server:
    build:
      context: ./ftp-server
      dockerfile: Dockerfile
    container_name: ctf-operation-silent-transfer-ftp-server
    hostname: ftp-server
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "operation-silent-transfer"
    networks:
      ctf-operation-silent-transfer-net:
        ipv4_address: 172.23.195.12
    ports:
      - "21"
    stdin_open: true
    tty: true

networks:
  ctf-operation-silent-transfer-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.195.0/24
          gateway: 172.23.195.1
  ctf-instances-network:
    external: true
