version: '3.8'
services:
  victim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ctf-realistic-memory-forensics-advanced-victim
    hostname: victim
    networks:
      ctf-network:
        ipv4_address: 172.24.193.174
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-realistic-memory-forensics-advanced-attacker
    hostname: attacker
    cap_add:
      - NET_RAW
      - NET_ADMIN
    networks:
      ctf-network:
        ipv4_address: 172.24.193.3
      ctf-instances-network: {}
networks:
  ctf-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.193.0/24
          gateway: 172.24.193.1
  ctf-instances-network:
    external: true
    name: ctf-instances-network
