version: '3.8'

services:
  ctf-corporate-network-reconnaissance-lab-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-corporate-network-reconnaissance-lab-attacker
    hostname: scanner-workstation
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "corporate-network-reconnaissance-lab"
    networks:
      ctf-corporate-network-reconnaissance-lab-net:
        ipv4_address: 172.23.193.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-corporate-network-reconnaissance-lab-linux-server:
    build:
      context: ./linux-server
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-reconnaissance-lab-linux-server
    hostname: linux-server
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-reconnaissance-lab"
    networks:
      ctf-corporate-network-reconnaissance-lab-net:
        ipv4_address: 172.23.193.194
    ports:
      - "22"
      - "21"
      - "80"
    stdin_open: true
    tty: true

  ctf-corporate-network-reconnaissance-lab-windows-workstation:
    build:
      context: ./windows-workstation
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-reconnaissance-lab-windows-workstation
    hostname: windows-workstation
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-reconnaissance-lab"
    networks:
      ctf-corporate-network-reconnaissance-lab-net:
        ipv4_address: 172.23.193.11
    ports:
      - "445"
    stdin_open: true
    tty: true

  ctf-corporate-network-reconnaissance-lab-embedded-device:
    build:
      context: ./embedded-device
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-reconnaissance-lab-embedded-device
    hostname: embedded-device
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-reconnaissance-lab"
    networks:
      ctf-corporate-network-reconnaissance-lab-net:
        ipv4_address: 172.23.193.12
    ports:
      - "80"
    stdin_open: true
    tty: true

  ctf-corporate-network-reconnaissance-lab-network-appliance:
    build:
      context: ./network-appliance
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-reconnaissance-lab-network-appliance
    hostname: network-appliance
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-reconnaissance-lab"
    networks:
      ctf-corporate-network-reconnaissance-lab-net:
        ipv4_address: 172.23.193.13
    ports:
      - "22"
    stdin_open: true
    tty: true

networks:
  ctf-corporate-network-reconnaissance-lab-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.193.0/24
          gateway: 172.23.193.1
  ctf-instances-network:
    external: true
