version: '3.8'

services:
  ctf-network-topology-infiltration-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-network-topology-infiltration-attacker
    hostname: attacker-machine
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "network-topology-infiltration"
    networks:
      ctf-network-topology-infiltration-net:
        ipv4_address: 172.23.206.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-network-topology-infiltration-hidden-network-alpha:
    build:
      context: ./hidden-network-alpha
      dockerfile: Dockerfile
    container_name: ctf-network-topology-infiltration-hidden-network-alpha
    hostname: hidden-network-alpha
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "network-topology-infiltration"
    networks:
      ctf-network-topology-infiltration-net:
        ipv4_address: 172.23.206.114
    ports:
      - "22"
      - "21"
    stdin_open: true
    tty: true

  ctf-network-topology-infiltration-restricted-subnet-beta:
    build:
      context: ./restricted-subnet-beta
      dockerfile: Dockerfile
    container_name: ctf-network-topology-infiltration-restricted-subnet-beta
    hostname: restricted-subnet-beta
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "network-topology-infiltration"
    networks:
      ctf-network-topology-infiltration-net:
        ipv4_address: 172.23.206.11
    ports:
      - "80"
    stdin_open: true
    tty: true

  ctf-network-topology-infiltration-monitoring-gateway:
    build:
      context: ./monitoring-gateway
      dockerfile: Dockerfile
    container_name: ctf-network-topology-infiltration-monitoring-gateway
    hostname: monitoring-gateway
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "network-topology-infiltration"
    networks:
      ctf-network-topology-infiltration-net:
        ipv4_address: 172.23.206.12
    ports:
      - "22"
    stdin_open: true
    tty: true

networks:
  ctf-network-topology-infiltration-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.206.0/24
          gateway: 172.23.206.1
  ctf-instances-network:
    external: true
