version: '3.8'

services:
  ctf-corporate-network-reconnaissance-challenge-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-corporate-network-reconnaissance-challenge-attacker
    hostname: attacker-workstation
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "corporate-network-reconnaissance-challenge"
    networks:
      ctf-corporate-network-reconnaissance-challenge-net:
        ipv4_address: 172.23.206.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-corporate-network-reconnaissance-challenge-corporate-fileserver:
    build:
      context: ./corporate-fileserver
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-reconnaissance-challenge-corporate-fileserver
    hostname: corporate-fileserver
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-reconnaissance-challenge"
    networks:
      ctf-corporate-network-reconnaissance-challenge-net:
        ipv4_address: 172.23.206.68
    ports:
      - "21"
      - "445"
      - "22"
    stdin_open: true
    tty: true

  ctf-corporate-network-reconnaissance-challenge-development-webserver:
    build:
      context: ./development-webserver
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-reconnaissance-challenge-development-webserver
    hostname: development-webserver
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-reconnaissance-challenge"
    networks:
      ctf-corporate-network-reconnaissance-challenge-net:
        ipv4_address: 172.23.206.11
    ports:
      - "80"
      - "22"
    stdin_open: true
    tty: true

  ctf-corporate-network-reconnaissance-challenge-backup-storage:
    build:
      context: ./backup-storage
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-reconnaissance-challenge-backup-storage
    hostname: backup-storage
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-reconnaissance-challenge"
    networks:
      ctf-corporate-network-reconnaissance-challenge-net:
        ipv4_address: 172.23.206.12
    stdin_open: true
    tty: true

networks:
  ctf-corporate-network-reconnaissance-challenge-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.206.0/24
          gateway: 172.23.206.1
  ctf-instances-network:
    external: true
