version: '3.8'

services:
  ctf-corporate-network-reconnaissance-challenge-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-corporate-network-reconnaissance-challenge-attacker
    hostname: attacker
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "corporate-network-reconnaissance-challenge"
    networks:
      ctf-corporate-network-reconnaissance-challenge-net:
        ipv4_address: 172.23.206.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-corporate-network-reconnaissance-challenge-webserver-alpha:
    build:
      context: ./webserver-alpha
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-reconnaissance-challenge-webserver-alpha
    hostname: webserver-alpha
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-reconnaissance-challenge"
    networks:
      ctf-corporate-network-reconnaissance-challenge-net:
        ipv4_address: 172.23.206.57
    ports:
      - "80"
      - "443"
      - "22"
      - "21"
    stdin_open: true
    tty: true

  ctf-corporate-network-reconnaissance-challenge-fileserver-beta:
    build:
      context: ./fileserver-beta
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-reconnaissance-challenge-fileserver-beta
    hostname: fileserver-beta
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-reconnaissance-challenge"
    networks:
      ctf-corporate-network-reconnaissance-challenge-net:
        ipv4_address: 172.23.206.11
    ports:
      - "445"
      - "22"
    stdin_open: true
    tty: true

  ctf-corporate-network-reconnaissance-challenge-database-gamma:
    build:
      context: ./database-gamma
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-reconnaissance-challenge-database-gamma
    hostname: database-gamma
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-reconnaissance-challenge"
    networks:
      ctf-corporate-network-reconnaissance-challenge-net:
        ipv4_address: 172.23.206.12
    ports:
      - "22"
    stdin_open: true
    tty: true

networks:
  ctf-corporate-network-reconnaissance-challenge-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.206.0/24
          gateway: 172.23.206.1
  ctf-instances-network:
    external: true
