version: '3.8'

services:
  ctf-anonymous-ftp-misconfiguration-ftp-server:
    build:
      context: ./ftp-server
      dockerfile: Dockerfile
    container_name: ctf-anonymous-ftp-misconfiguration-ftp-server
    hostname: ftp-server
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "anonymous-ftp-misconfiguration"
    networks:
      ctf-anonymous-ftp-misconfiguration-net:
        ipv4_address: 172.23.193.63
    ports:
      - "21"
    stdin_open: true
    tty: true

  ctf-anonymous-ftp-misconfiguration-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-anonymous-ftp-misconfiguration-attacker
    hostname: attacker-machine
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "anonymous-ftp-misconfiguration"
    networks:
      ctf-anonymous-ftp-misconfiguration-net:
        ipv4_address: 172.23.193.3
      ctf-instances-network:
    stdin_open: true
    tty: true

networks:
  ctf-anonymous-ftp-misconfiguration-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.193.0/24
          gateway: 172.23.193.1
  ctf-instances-network:
    external: true
