version: '3.8'

services:
  ctf-corporate-ftp-file-discovery-ftp-server:
    build:
      context: ./ftp-server
      dockerfile: Dockerfile
    container_name: ctf-corporate-ftp-file-discovery-ftp-server
    hostname: ftp-server
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-ftp-file-discovery"
    networks:
      ctf-corporate-ftp-file-discovery-net:
        ipv4_address: 172.23.196.107
    ports:
      - "21"
      - "22"
    stdin_open: true
    tty: true

  ctf-corporate-ftp-file-discovery-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-corporate-ftp-file-discovery-attacker
    hostname: attacker-machine
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "corporate-ftp-file-discovery"
    networks:
      ctf-corporate-ftp-file-discovery-net:
        ipv4_address: 172.23.196.3
      ctf-instances-network:
    stdin_open: true
    tty: true

networks:
  ctf-corporate-ftp-file-discovery-net:
    driver: bridge
    ipam:
      config:
        - subnet: [object Object]
  ctf-instances-network:
    external: true
          gateway: 172.23.196.1
  ctf-instances-network:
    external: true
