version: '3.8'

services:
  ctf-memory-forensics-investigation-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-memory-forensics-investigation-attacker
    hostname: attacker-machine
    networks:
      ctf-memory-forensics-investigation-net:
        ipv4_address: 172.23.199.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-memory-forensics-investigation-victim-machine:
    build:
      context: ./victim-machine
      dockerfile: Dockerfile
    container_name: ctf-memory-forensics-investigation-victim-machine
    hostname: victim-machine
    networks:
      ctf-memory-forensics-investigation-net:
        ipv4_address: 172.23.199.10
    stdin_open: true
    tty: true

networks:
  ctf-memory-forensics-investigation-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.199.0/24
          gateway: 172.23.199.1
  ctf-instances-network:
    external: true
