services:
  ftp-server:
    build:
      context: ./ftp-server
      dockerfile: Dockerfile
    container_name: ctf-corporate-ftp-infiltration-ftp-server
    networks:
      ctf-corporate-ftp-infiltration-net:
        ipv4_address: 172.24.193.122
    restart: unless-stopped
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: ctf-corporate-ftp-infiltration-attacker
    networks:
      ctf-corporate-ftp-infiltration-net:
        ipv4_address: 172.24.193.3
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
networks:
  ctf-corporate-ftp-infiltration-net:
    name: ctf-corporate-ftp-infiltration-net
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.24.193.0/24
          gateway: 172.24.193.1
