services:
  corporate-ftp-server:
    build:
      context: ./corporate-ftp-server
      dockerfile: Dockerfile
    container_name: ctf-corporate-ftp-infiltration-corporate-ftp-server
    networks:
      ctf-corporate-ftp-infiltration-net:
        ipv4_address: 172.23.208.188
    restart: unless-stopped
networks:
  ctf-corporate-ftp-infiltration-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.208.0/24
          gateway: 172.23.208.1
  ctf-instances-network:
    external: true
