version: '3.8'

services:
  ctf-datacorp-file-server-audit-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-datacorp-file-server-audit-attacker
    hostname: security-auditor
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "datacorp-file-server-audit"
    networks:
      ctf-datacorp-file-server-audit-net:
        ipv4_address: 172.29.193.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-datacorp-file-server-audit-corporate-fileserver:
    build:
      context: ./corporate-fileserver
      dockerfile: Dockerfile
    container_name: ctf-datacorp-file-server-audit-corporate-fileserver
    hostname: corporate-fileserver
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "datacorp-file-server-audit"
    networks:
      ctf-datacorp-file-server-audit-net:
        ipv4_address: 172.29.193.129
    ports:
      - "21"
    stdin_open: true
    tty: true

networks:
  ctf-datacorp-file-server-audit-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.193.0/24
          gateway: 172.29.193.1
  ctf-instances-network:
    external: true
