services:
  crypto-vault:
    build:
      context: ./crypto-vault
      dockerfile: Dockerfile
    container_name: ctf-ancient-cipher-vault-crypto-vault
    networks:
      ctf-ancient-cipher-vault-net:
        ipv4_address: 172.23.208.70
    restart: unless-stopped
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: ctf-ancient-cipher-vault-attacker
    networks:
      ctf-ancient-cipher-vault-net:
        ipv4_address: 172.23.208.3
      ctf-instances-network: {}
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
networks:
  ctf-ancient-cipher-vault-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.208.0/24
          gateway: 172.23.208.1
  ctf-instances-network:
    external: true
