services:
  samba-server:
    build:
      context: ./samba-server
      dockerfile: Dockerfile
    container_name: ctf-eternal-blue-samba-exploitation-samba-server
    networks:
      ctf-eternal-blue-samba-exploitation-net:
        ipv4_address: 172.26.193.16
    restart: unless-stopped
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: ctf-eternal-blue-samba-exploitation-attacker
    networks:
      ctf-eternal-blue-samba-exploitation-net:
        ipv4_address: 172.26.193.3
      ctf-instances-network: {}
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
networks:
  ctf-eternal-blue-samba-exploitation-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.193.0/24
          gateway: 172.26.193.1
  ctf-instances-network:
    external: true
