version: '3.8'

services:
  ctf-financial-firm-ftp-breach-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-financial-firm-ftp-breach-attacker
    hostname: pentester-workstation
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "financial-firm-ftp-breach"
    networks:
      ctf-financial-firm-ftp-breach-net:
        ipv4_address: 172.23.199.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-financial-firm-ftp-breach-corporate-fileserver:
    build:
      context: ./corporate-fileserver
      dockerfile: Dockerfile
    container_name: ctf-financial-firm-ftp-breach-corporate-fileserver
    hostname: corporate-fileserver
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "financial-firm-ftp-breach"
    networks:
      ctf-financial-firm-ftp-breach-net:
        ipv4_address: 172.23.199.36
    ports:
      - "21"
    stdin_open: true
    tty: true

networks:
  ctf-financial-firm-ftp-breach-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.199.0/24
          gateway: 172.23.199.1
  ctf-instances-network:
    external: true
