services:
  samba-server:
    build:
      context: ./samba-server
      dockerfile: Dockerfile
    container_name: ctf-samba-guest-access-exploitation-samba-server
    networks:
      ctf-samba-guest-access-exploitation-net:
        ipv4_address: 172.23.145.43
    restart: unless-stopped
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: ctf-samba-guest-access-exploitation-attacker
    networks:
      ctf-samba-guest-access-exploitation-net:
        ipv4_address: 172.23.145.3
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
networks:
  ctf-samba-guest-access-exploitation-net:
    name: ctf-samba-guest-access-exploitation-net
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.23.145.0/24
          gateway: 172.23.145.1
