services:
  ctf-blueprint-heist-construction-corp-ftp-breach-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-blueprint-heist-construction-corp-ftp-breach-attacker
    hostname: pentester
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "blueprint-heist-construction-corp-ftp-breach"
    networks:
      ctf-blueprint-heist-construction-corp-ftp-breach-net:
        ipv4_address: 172.23.205.3
      ctf-instances-network:
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true

  ctf-blueprint-heist-construction-corp-ftp-breach-corporate-ftp:
    build:
      context: ./corporate-ftp
      dockerfile: Dockerfile
    container_name: ctf-blueprint-heist-construction-corp-ftp-breach-corporate-ftp
    hostname: corporate-ftp
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "blueprint-heist-construction-corp-ftp-breach"
    networks:
      ctf-blueprint-heist-construction-corp-ftp-breach-net:
        ipv4_address: 172.23.205.53
    ports:
      - "21"
    stdin_open: true
    tty: true

networks:
  ctf-blueprint-heist-construction-corp-ftp-breach-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.205.0/24
          gateway: 172.23.205.1
  ctf-instances-network:
    external: true
