version: '3.8'
services:
  victim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ctf-xss-ssh-ftp-eternalblue-victim
    hostname: victim
    networks:
      ctf-network:
        ipv4_address: 172.23.199.10
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-xss-ssh-ftp-eternalblue-attacker
    hostname: attacker
    networks:
      ctf-network:
        ipv4_address: 172.23.199.3
      ctf-instances-network: {}
networks:
  ctf-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.199.0/24
          gateway: 172.23.199.1
  ctf-instances-network:
    external: true
    name: ctf-instances-network
