version: '3.8'

services:
  ctf-corporate-data-leak-investigation-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-corporate-data-leak-investigation-attacker
    hostname: attacker
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "corporate-data-leak-investigation"
    networks:
      ctf-corporate-data-leak-investigation-net:
        ipv4_address: 172.23.195.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-corporate-data-leak-investigation-ftp-server:
    build:
      context: ./ftp-server
      dockerfile: Dockerfile
    container_name: ctf-corporate-data-leak-investigation-ftp-server
    hostname: ftp-server
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-data-leak-investigation"
    networks:
      ctf-corporate-data-leak-investigation-net:
        ipv4_address: 172.23.195.130
    ports:
      - "21"
      - "22"
    stdin_open: true
    tty: true

networks:
  ctf-corporate-data-leak-investigation-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.195.0/24
          gateway: 172.23.195.1
  ctf-instances-network:
    external: true
