services:
  techcorp-ftp-server:
    build:
      context: ./techcorp-ftp-server
      dockerfile: Dockerfile
    container_name: ctf-corporate-data-breach-techcorp-ftp-server
    networks:
      ctf-corporate-data-breach-net:
        ipv4_address: 172.23.208.168
    restart: unless-stopped
networks:
  ctf-corporate-data-breach-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.208.0/24
          gateway: 172.23.208.1
  ctf-instances-network:
    external: true
