services:
  techcorp-ftp:
    build:
      context: ./techcorp-ftp
      dockerfile: Dockerfile
    container_name: ctf-corporate-data-breach-techcorp-ftp
    networks:
      ctf-corporate-data-breach-net:
        ipv4_address: 172.25.193.34
    restart: unless-stopped
networks:
  ctf-corporate-data-breach-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.193.0/24
          gateway: 172.25.193.1
  ctf-instances-network:
    external: true
