services:
  techcorp-portal:
    build:
      context: ./techcorp-portal
      dockerfile: Dockerfile
    container_name: ctf-corporate-data-breach-techcorp-portal
    networks:
      ctf-corporate-data-breach-net:
        ipv4_address: 172.25.195.153
    restart: unless-stopped
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: ctf-corporate-data-breach-attacker
    networks:
      ctf-corporate-data-breach-net:
        ipv4_address: 172.25.195.3
      ctf-instances-network: {}
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
networks:
  ctf-corporate-data-breach-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.195.0/24
          gateway: 172.25.195.1
  ctf-instances-network:
    external: true
