version: '3.8'

services:
  ctf-digital-forensics-memory-analysis-investigation-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-digital-forensics-memory-analysis-investigation-attacker
    hostname: attacker-workstation
    networks:
      ctf-digital-forensics-memory-analysis-investigation-net:
        ipv4_address: 172.28.193.3
    stdin_open: true
    tty: true

  ctf-digital-forensics-memory-analysis-investigation-evidence-server:
    build:
      context: ./evidence-server
      dockerfile: Dockerfile
    container_name: ctf-digital-forensics-memory-analysis-investigation-evidence-server
    hostname: evidence-server
    networks:
      ctf-digital-forensics-memory-analysis-investigation-net:
        ipv4_address: 172.28.193.10
    ports:
      - "21"
      - "80"
    stdin_open: true
    tty: true

networks:
  ctf-digital-forensics-memory-analysis-investigation-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.193.0/24
          gateway: 172.28.193.1
