version: '3.8'
services:
  victim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ctf-nmap-discovery-mystery-victim
    hostname: victim
    networks:
      ctf-network:
        ipv4_address: 10.189.193.10
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-nmap-discovery-mystery-attacker
    hostname: attacker
    networks:
      ctf-network:
        ipv4_address: 10.189.193.100
    shm_size: 512m
networks:
  ctf-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.189.193.0/24
          gateway: 10.189.193.1
