version: '3.8'

services:
  ctf-project-archive-infiltration-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-project-archive-infiltration-attacker
    hostname: attacker
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "project-archive-infiltration"
    networks:
      ctf-project-archive-infiltration-net:
        ipv4_address: 172.23.196.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-project-archive-infiltration-ftp-server:
    build:
      context: ./ftp-server
      dockerfile: Dockerfile
    container_name: ctf-project-archive-infiltration-ftp-server
    hostname: ftp-server
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "project-archive-infiltration"
    networks:
      ctf-project-archive-infiltration-net:
        ipv4_address: 172.23.196.88
    ports:
      - "21"
      - "22"
    stdin_open: true
    tty: true

networks:
  ctf-project-archive-infiltration-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.196.0/24
          gateway: 172.23.196.1
  ctf-instances-network:
    external: true
