services:
  samba-server:
    build:
      context: ./samba-server
      dockerfile: Dockerfile
    container_name: ctf-corporate-file-share-breach-samba-server
    networks:
      ctf-corporate-file-share-breach-net:
        ipv4_address: 172.25.193.86
    restart: unless-stopped
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: ctf-corporate-file-share-breach-attacker
    networks:
      ctf-corporate-file-share-breach-net:
        ipv4_address: 172.25.193.3
      ctf-instances-network: {}
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
networks:
  ctf-corporate-file-share-breach-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.193.0/24
          gateway: 172.25.193.1
  ctf-instances-network:
    external: true
