services:
  ftp-server:
    build:
      context: ./ftp-server
      dockerfile: Dockerfile
    container_name: ctf-corporate-ftp-breach-ftp-server
    networks:
      ctf-corporate-ftp-breach-net:
        ipv4_address: 172.29.193.127
    restart: unless-stopped
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: ctf-corporate-ftp-breach-attacker
    networks:
      ctf-corporate-ftp-breach-net:
        ipv4_address: 172.29.193.3
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
networks:
  ctf-corporate-ftp-breach-net:
    name: ctf-corporate-ftp-breach-net
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.29.193.0/24
          gateway: 172.29.193.1
