version: '3.8'

services:
  ctf-corporate-ftp-breach-ftp-server:
    build:
      context: ./ftp-server
      dockerfile: Dockerfile
    container_name: ctf-corporate-ftp-breach-ftp-server
    hostname: ftp-server
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-ftp-breach"
    networks:
      ctf-corporate-ftp-breach-net:
        ipv4_address: 172.29.193.125
    ports:
      - "21"
      - "22"
    stdin_open: true
    tty: true

  ctf-corporate-ftp-breach-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-corporate-ftp-breach-attacker
    hostname: attacker
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "corporate-ftp-breach"
    networks:
      ctf-corporate-ftp-breach-net:
        ipv4_address: 172.29.193.3
      ctf-instances-network:
    stdin_open: true
    tty: true

networks:
  ctf-corporate-ftp-breach-net:
    driver: bridge
    ipam:
      config:
        - subnet: [object Object]
  ctf-instances-network:
    external: true
          gateway: 172.29.193.1
  ctf-instances-network:
    external: true
