services:
  ftp-server:
    build:
      context: ./ftp-server
      dockerfile: Dockerfile
    container_name: ctf-corporate-ftp-breach-ftp-server
    networks:
      ctf-corporate-ftp-breach-net:
        ipv4_address: 172.23.209.97
    restart: unless-stopped
networks:
  ctf-corporate-ftp-breach-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.209.0/24
          gateway: 172.23.209.1
  ctf-instances-network:
    external: true
