version: '3.8'

services:
  ctf-corporate-data-breach-samba-share-infiltration-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-corporate-data-breach-samba-share-infiltration-attacker
    hostname: attacker-workstation
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "corporate-data-breach-samba-share-infiltration"
    networks:
      ctf-corporate-data-breach-samba-share-infiltration-net:
        ipv4_address: 172.29.193.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-corporate-data-breach-samba-share-infiltration-corporate-fileserver:
    build:
      context: ./corporate-fileserver
      dockerfile: Dockerfile
    container_name: ctf-corporate-data-breach-samba-share-infiltration-corporate-fileserver
    hostname: corporate-fileserver
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-data-breach-samba-share-infiltration"
    networks:
      ctf-corporate-data-breach-samba-share-infiltration-net:
        ipv4_address: 172.29.193.66
    ports:
      - "22"
    stdin_open: true
    tty: true

networks:
  ctf-corporate-data-breach-samba-share-infiltration-net:
    driver: bridge
    ipam:
      config:
        - subnet: [object Object]
  ctf-instances-network:
    external: true
          gateway: 172.29.193.1
  ctf-instances-network:
    external: true
