version: '3.8'

services:
  ctf-corporate-breach-investigation-attacker-workstation:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-corporate-breach-investigation-attacker-workstation
    hostname: attacker-workstation
    networks:
      ctf-corporate-breach-investigation-net:
        ipv4_address: 172.23.198.3
    stdin_open: true
    tty: true

  ctf-corporate-breach-investigation-evidence-server:
    build:
      context: ./evidence-server
      dockerfile: Dockerfile
    container_name: ctf-corporate-breach-investigation-evidence-server
    hostname: evidence-server
    networks:
      ctf-corporate-breach-investigation-net:
        ipv4_address: 172.23.198.10
    ports:
      - "21"
      - "80"
    stdin_open: true
    tty: true

networks:
  ctf-corporate-breach-investigation-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.198.0/24
          gateway: 172.23.198.1
