version: '3.8'

services:
  ctf-corporate-network-discovery-lab-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-corporate-network-discovery-lab-attacker
    hostname: scanner-workstation
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "corporate-network-discovery-lab"
    networks:
      ctf-corporate-network-discovery-lab-net:
        ipv4_address: 172.23.193.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-corporate-network-discovery-lab-corporate-fileserver:
    build:
      context: ./corporate-fileserver
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-discovery-lab-corporate-fileserver
    hostname: corporate-fileserver
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-discovery-lab"
    networks:
      ctf-corporate-network-discovery-lab-net:
        ipv4_address: 172.23.193.18
    ports:
      - "21"
      - "22"
      - "445"
    stdin_open: true
    tty: true

  ctf-corporate-network-discovery-lab-legacy-system:
    build:
      context: ./legacy-system
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-discovery-lab-legacy-system
    hostname: legacy-system
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-discovery-lab"
    networks:
      ctf-corporate-network-discovery-lab-net:
        ipv4_address: 172.23.193.11
    ports:
      - "21"
      - "80"
    stdin_open: true
    tty: true

  ctf-corporate-network-discovery-lab-database-server:
    build:
      context: ./database-server
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-discovery-lab-database-server
    hostname: database-server
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-discovery-lab"
    networks:
      ctf-corporate-network-discovery-lab-net:
        ipv4_address: 172.23.193.12
    ports:
      - "22"
      - "80"
    stdin_open: true
    tty: true

networks:
  ctf-corporate-network-discovery-lab-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.193.0/24
          gateway: 172.23.193.1
  ctf-instances-network:
    external: true
