version: '3.8'

services:
  ctf-ftp-server-challenge-ftp-server:
    build:
      context: ./ftp-server
      dockerfile: Dockerfile
    container_name: ctf-ftp-server-challenge-ftp-server
    hostname: ftp-server
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "ftp-server-challenge"
    networks:
      ctf-ftp-server-challenge-net:
        ipv4_address: 172.24.193.135
    ports:
      - "21"
      - "22"
    stdin_open: true
    tty: true

  ctf-ftp-server-challenge-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-ftp-server-challenge-attacker
    hostname: attacker
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "ftp-server-challenge"
    networks:
      ctf-ftp-server-challenge-net:
        ipv4_address: 172.24.193.3
    stdin_open: true
    tty: true

networks:
  ctf-ftp-server-challenge-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.193.0/24
          gateway: 172.24.193.1
  ctf-instances-network:
    external: true
