version: '3.8'

services:
  ctf-corporate-data-breach-assessment-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-corporate-data-breach-assessment-attacker
    hostname: security-auditor
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "corporate-data-breach-assessment"
    networks:
      ctf-corporate-data-breach-assessment-net:
        ipv4_address: 172.23.201.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-corporate-data-breach-assessment-corporate-fileserver:
    build:
      context: ./corporate-fileserver
      dockerfile: Dockerfile
    container_name: ctf-corporate-data-breach-assessment-corporate-fileserver
    hostname: corporate-fileserver
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-data-breach-assessment"
    networks:
      ctf-corporate-data-breach-assessment-net:
        ipv4_address: 172.23.201.61
    ports:
      - "21"
    stdin_open: true
    tty: true

networks:
  ctf-corporate-data-breach-assessment-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.201.0/24
          gateway: 172.23.201.1
  ctf-instances-network:
    external: true
