version: '3.8'
services:
  victim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ctf-insecure-login-portal-victim
    hostname: victim
    networks:
      ctf-network:
        ipv4_address: 172.27.193.10
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-insecure-login-portal-attacker
    hostname: attacker
    networks:
      ctf-network:
        ipv4_address: 172.27.193.100
    shm_size: 512m
networks:
  ctf-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.193.0/24
          gateway: 172.27.193.1
