version: '3.8'

services:
  ctf-corporate-data-breach-via-smb-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-corporate-data-breach-via-smb-attacker
    hostname: attacker-workstation
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "corporate-data-breach-via-smb"
    networks:
      ctf-corporate-data-breach-via-smb-net:
        ipv4_address: 172.23.193.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-corporate-data-breach-via-smb-samba-fileserver:
    build:
      context: ./samba-fileserver
      dockerfile: Dockerfile
    container_name: ctf-corporate-data-breach-via-smb-samba-fileserver
    hostname: samba-fileserver
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-data-breach-via-smb"
    networks:
      ctf-corporate-data-breach-via-smb-net:
        ipv4_address: 172.23.193.152
    ports:
      - "22"
    stdin_open: true
    tty: true

networks:
  ctf-corporate-data-breach-via-smb-net:
    driver: bridge
    ipam:
      config:
        - subnet: [object Object]
  ctf-instances-network:
    external: true
          gateway: 172.23.193.1
  ctf-instances-network:
    external: true
