version: '3.8'

services:
  ctf-corporate-data-breach-via-smb-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-corporate-data-breach-via-smb-attacker
    hostname: attacker-workstation
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "corporate-data-breach-via-smb"
    networks:
      ctf-corporate-data-breach-via-smb-net:
        ipv4_address: 172.23.194.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-corporate-data-breach-via-smb-corporate-fileserver:
    build:
      context: ./corporate-fileserver
      dockerfile: Dockerfile
    container_name: ctf-corporate-data-breach-via-smb-corporate-fileserver
    hostname: corporate-fileserver
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-data-breach-via-smb"
    networks:
      ctf-corporate-data-breach-via-smb-net:
        ipv4_address: 172.23.194.48
    ports:
      - "22"
    stdin_open: true
    tty: true

networks:
  ctf-corporate-data-breach-via-smb-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.194.0/24
          gateway: 172.23.194.1
  ctf-instances-network:
    external: true
