services:
  samba-server:
    build:
      context: ./samba-server
      dockerfile: Dockerfile
    container_name: ctf-samba-anonymous-share-exploitation-samba-server
    networks:
      ctf-samba-anonymous-share-exploitation-net:
        ipv4_address: 172.23.145.164
    restart: unless-stopped
  attacker-kali:
    build:
      context: ./attacker-kali
      dockerfile: Dockerfile
    container_name: ctf-samba-anonymous-share-exploitation-attacker-kali
    networks:
      ctf-samba-anonymous-share-exploitation-net:
        ipv4_address: 172.23.145.3
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
networks:
  ctf-samba-anonymous-share-exploitation-net:
    name: ctf-samba-anonymous-share-exploitation-net
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.23.145.0/24
          gateway: 172.23.145.1
