services:
  ctf-project-phoenix-data-breach-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-project-phoenix-data-breach-attacker
    hostname: penetration-tester
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "project-phoenix-data-breach"
    networks:
      ctf-project-phoenix-data-breach-net:
        ipv4_address: 172.23.207.3
      ctf-instances-network:
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true

  ctf-project-phoenix-data-breach-corporate-fileserver:
    build:
      context: ./corporate-fileserver
      dockerfile: Dockerfile
    container_name: ctf-project-phoenix-data-breach-corporate-fileserver
    hostname: corporate-fileserver
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "project-phoenix-data-breach"
    networks:
      ctf-project-phoenix-data-breach-net:
        ipv4_address: 172.23.207.129
    ports:
      - "21"
    stdin_open: true
    tty: true

networks:
  ctf-project-phoenix-data-breach-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.207.0/24
          gateway: 172.23.207.1
  ctf-instances-network:
    external: true
