version: '3.8'

services:
  ctf-network-service-exploitation-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-network-service-exploitation-attacker
    hostname: attacker-machine
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "network-service-exploitation"
    networks:
      ctf-network-service-exploitation-net:
        ipv4_address: 172.26.193.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-network-service-exploitation-victim-server:
    build:
      context: ./victim-server
      dockerfile: Dockerfile
    container_name: ctf-network-service-exploitation-victim-server
    hostname: victim-server
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "network-service-exploitation"
    networks:
      ctf-network-service-exploitation-net:
        ipv4_address: 172.26.193.115
    ports:
      - "22"
    stdin_open: true
    tty: true

networks:
  ctf-network-service-exploitation-net:
    driver: bridge
    ipam:
      config:
        - subnet: [object Object]
  ctf-instances-network:
    external: true
          gateway: 172.26.193.1
  ctf-instances-network:
    external: true
