services:
  fileserver:
    build:
      context: ./fileserver
      dockerfile: Dockerfile
    container_name: ctf-samba-anonymous-shares-fileserver
    networks:
      ctf-samba-anonymous-shares-net:
        ipv4_address: 172.21.193.69
    restart: unless-stopped
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: ctf-samba-anonymous-shares-attacker
    networks:
      ctf-samba-anonymous-shares-net:
        ipv4_address: 172.21.193.3
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
networks:
  ctf-samba-anonymous-shares-net:
    name: ctf-samba-anonymous-shares-net
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.21.193.0/24
          gateway: 172.21.193.1
