version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=webapp
      - MYSQL_PASSWORD=web123
      - MYSQL_DATABASE=corporate_network
    volumes:
      - ./network_config.xml:/etc/network/topology.xml

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass123
      - MYSQL_DATABASE=corporate_network
      - MYSQL_USER=webapp
      - MYSQL_PASSWORD=web123
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"