services:
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: ctf-corporate-breach-boot2root-attacker
    networks:
      ctf-corporate-breach-boot2root-net:
        ipv4_address: 172.20.145.3
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
  cybercorp-server:
    build:
      context: ./cybercorp-server
      dockerfile: Dockerfile
    container_name: ctf-corporate-breach-boot2root-cybercorp-server
    networks:
      ctf-corporate-breach-boot2root-net:
        ipv4_address: 172.20.145.87
    restart: unless-stopped
networks:
  ctf-corporate-breach-boot2root-net:
    name: ctf-corporate-breach-boot2root-net
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.20.145.0/24
          gateway: 172.20.145.1
