version: '3.8'

services:
  ctf-corporate-data-breach-misconfigured-samba-server-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-corporate-data-breach-misconfigured-samba-server-attacker
    hostname: penetration-tester
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "corporate-data-breach-misconfigured-samba-server"
    networks:
      ctf-corporate-data-breach-misconfigured-samba-server-net:
        ipv4_address: 172.23.193.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-corporate-data-breach-misconfigured-samba-server-corporate-fileserver:
    build:
      context: ./corporate-fileserver
      dockerfile: Dockerfile
    container_name: ctf-corporate-data-breach-misconfigured-samba-server-corporate-fileserver
    hostname: corporate-fileserver
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-data-breach-misconfigured-samba-server"
    networks:
      ctf-corporate-data-breach-misconfigured-samba-server-net:
        ipv4_address: 172.23.193.94
    ports:
      - "445"
      - "22"
    stdin_open: true
    tty: true

networks:
  ctf-corporate-data-breach-misconfigured-samba-server-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.193.0/24
          gateway: 172.23.193.1
  ctf-instances-network:
    external: true
