version: '3.8'

services:
  ctf-multi-os-network-reconnaissance-laboratory-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-multi-os-network-reconnaissance-laboratory-attacker
    hostname: scanner-kali
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "multi-os-network-reconnaissance-laboratory"
    networks:
      ctf-multi-os-network-reconnaissance-laboratory-net:
        ipv4_address: 172.23.193.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-multi-os-network-reconnaissance-laboratory-ubuntu-webserver:
    build:
      context: ./ubuntu-webserver
      dockerfile: Dockerfile
    container_name: ctf-multi-os-network-reconnaissance-laboratory-ubuntu-webserver
    hostname: ubuntu-webserver
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "multi-os-network-reconnaissance-laboratory"
    networks:
      ctf-multi-os-network-reconnaissance-laboratory-net:
        ipv4_address: 172.23.193.174
    ports:
      - "80"
      - "443"
      - "22"
      - "21"
    stdin_open: true
    tty: true

  ctf-multi-os-network-reconnaissance-laboratory-centos-enterprise:
    build:
      context: ./centos-enterprise
      dockerfile: Dockerfile
    container_name: ctf-multi-os-network-reconnaissance-laboratory-centos-enterprise
    hostname: centos-enterprise
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "multi-os-network-reconnaissance-laboratory"
    networks:
      ctf-multi-os-network-reconnaissance-laboratory-net:
        ipv4_address: 172.23.193.11
    ports:
      - "22"
      - "445"
    stdin_open: true
    tty: true

  ctf-multi-os-network-reconnaissance-laboratory-alpine-minimal:
    build:
      context: ./alpine-minimal
      dockerfile: Dockerfile
    container_name: ctf-multi-os-network-reconnaissance-laboratory-alpine-minimal
    hostname: alpine-minimal
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "multi-os-network-reconnaissance-laboratory"
    networks:
      ctf-multi-os-network-reconnaissance-laboratory-net:
        ipv4_address: 172.23.193.12
    ports:
      - "22"
    stdin_open: true
    tty: true

  ctf-multi-os-network-reconnaissance-laboratory-debian-legacy:
    build:
      context: ./debian-legacy
      dockerfile: Dockerfile
    container_name: ctf-multi-os-network-reconnaissance-laboratory-debian-legacy
    hostname: debian-legacy
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "multi-os-network-reconnaissance-laboratory"
    networks:
      ctf-multi-os-network-reconnaissance-laboratory-net:
        ipv4_address: 172.23.193.13
    ports:
      - "21"
    stdin_open: true
    tty: true

networks:
  ctf-multi-os-network-reconnaissance-laboratory-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.193.0/24
          gateway: 172.23.193.1
  ctf-instances-network:
    external: true
