services:
  fileserver:
    build:
      context: ./fileserver
      dockerfile: Dockerfile
    container_name: ctf-corporate-file-share-fileserver
    networks:
      ctf-corporate-file-share-net:
        ipv4_address: 172.23.210.45
    restart: unless-stopped
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: ctf-corporate-file-share-attacker
    networks:
      ctf-corporate-file-share-net:
        ipv4_address: 172.23.210.3
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
networks:
  ctf-corporate-file-share-net:
    name: ctf-corporate-file-share-net
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.23.210.0/24
          gateway: 172.23.210.1
