version: '3.8'

services:
  ctf-banking-security-audit-legacy-ftp-breach-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-banking-security-audit-legacy-ftp-breach-attacker
    hostname: attacker-workstation
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "banking-security-audit-legacy-ftp-breach"
    networks:
      ctf-banking-security-audit-legacy-ftp-breach-net:
        ipv4_address: 172.23.198.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-banking-security-audit-legacy-ftp-breach-bank-fileserver:
    build:
      context: ./bank-fileserver
      dockerfile: Dockerfile
    container_name: ctf-banking-security-audit-legacy-ftp-breach-bank-fileserver
    hostname: bank-fileserver
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "banking-security-audit-legacy-ftp-breach"
    networks:
      ctf-banking-security-audit-legacy-ftp-breach-net:
        ipv4_address: 172.23.198.124
    ports:
      - "21"
    stdin_open: true
    tty: true

networks:
  ctf-banking-security-audit-legacy-ftp-breach-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.198.0/24
          gateway: 172.23.198.1
  ctf-instances-network:
    external: true
