version: '3.8'

services:
  ctf-corporate-network-discovery-challenge-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-corporate-network-discovery-challenge-attacker
    hostname: attacker-workstation
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "corporate-network-discovery-challenge"
    networks:
      ctf-corporate-network-discovery-challenge-net:
        ipv4_address: 172.27.193.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-corporate-network-discovery-challenge-corporate-gateway:
    build:
      context: ./corporate-gateway
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-discovery-challenge-corporate-gateway
    hostname: corporate-gateway
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-discovery-challenge"
    networks:
      ctf-corporate-network-discovery-challenge-net:
        ipv4_address: 172.27.193.53
    ports:
      - "22"
      - "21"
      - "80"
    stdin_open: true
    tty: true

  ctf-corporate-network-discovery-challenge-file-server:
    build:
      context: ./file-server
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-discovery-challenge-file-server
    hostname: file-server
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-discovery-challenge"
    networks:
      ctf-corporate-network-discovery-challenge-net:
        ipv4_address: 172.27.193.11
    ports:
      - "445"
    stdin_open: true
    tty: true

  ctf-corporate-network-discovery-challenge-database-host:
    build:
      context: ./database-host
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-discovery-challenge-database-host
    hostname: database-host
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-discovery-challenge"
    networks:
      ctf-corporate-network-discovery-challenge-net:
        ipv4_address: 172.27.193.12
    stdin_open: true
    tty: true

networks:
  ctf-corporate-network-discovery-challenge-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.193.0/24
          gateway: 172.27.193.1
  ctf-instances-network:
    external: true
