services:
  target-server:
    build:
      context: ./target-server
      dockerfile: Dockerfile
    container_name: ctf-network-recon-challenge-target-server
    networks:
      ctf-network-recon-challenge-net:
        ipv4_address: 172.23.147.129
    restart: unless-stopped
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: ctf-network-recon-challenge-attacker
    networks:
      ctf-network-recon-challenge-net:
        ipv4_address: 172.23.147.3
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
networks:
  ctf-network-recon-challenge-net:
    name: ctf-network-recon-challenge-net
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.23.147.0/24
          gateway: 172.23.147.1
