services:
  ctf-digital-media-archive-breach-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-digital-media-archive-breach-attacker
    hostname: attacker
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "digital-media-archive-breach"
    networks:
      ctf-digital-media-archive-breach-net:
        ipv4_address: 172.27.193.3
      ctf-instances-network:
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true

  ctf-digital-media-archive-breach-ftp-server:
    build:
      context: ./ftp-server
      dockerfile: Dockerfile
    container_name: ctf-digital-media-archive-breach-ftp-server
    hostname: ftp-server
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "digital-media-archive-breach"
    networks:
      ctf-digital-media-archive-breach-net:
        ipv4_address: 172.27.193.34
    ports:
      - "21"
    stdin_open: true
    tty: true

networks:
  ctf-digital-media-archive-breach-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.193.0/24
          gateway: 172.27.193.1
  ctf-instances-network:
    external: true
