services:
  fileserver:
    build:
      context: ./fileserver
      dockerfile: Dockerfile
    container_name: ctf-eternalblue-samba-exploit-fileserver
    networks:
      ctf-eternalblue-samba-exploit-net:
        ipv4_address: 172.23.209.70
    restart: unless-stopped
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: ctf-eternalblue-samba-exploit-attacker
    networks:
      ctf-eternalblue-samba-exploit-net:
        ipv4_address: 172.23.209.3
      ctf-instances-network: {}
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
networks:
  ctf-eternalblue-samba-exploit-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.209.0/24
          gateway: 172.23.209.1
  ctf-instances-network:
    external: true
