services:
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: ctf-eternalblue-samba-exploit-attacker
    networks:
      ctf-eternalblue-samba-exploit-net:
        ipv4_address: 172.28.145.3
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
  victim:
    build:
      context: ./victim
      dockerfile: Dockerfile
    container_name: ctf-eternalblue-samba-exploit-victim
    networks:
      ctf-eternalblue-samba-exploit-net:
        ipv4_address: 172.28.145.90
    restart: unless-stopped
networks:
  ctf-eternalblue-samba-exploit-net:
    name: ctf-eternalblue-samba-exploit-net
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.28.145.0/24
          gateway: 172.28.145.1
