services:
  samba-fileserver:
    build:
      context: ./samba-fileserver
      dockerfile: Dockerfile
    container_name: ctf-eternalblue-samba-exploitation-samba-fileserver
    networks:
      ctf-eternalblue-samba-exploitation-net:
        ipv4_address: 172.24.193.45
    restart: unless-stopped
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: ctf-eternalblue-samba-exploitation-attacker
    networks:
      ctf-eternalblue-samba-exploitation-net:
        ipv4_address: 172.24.193.3
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
networks:
  ctf-eternalblue-samba-exploitation-net:
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.24.193.0/24
          gateway: 172.24.193.1
