services:
  samba-victim:
    build:
      context: ./samba-victim
      dockerfile: Dockerfile
    container_name: ctf-eternalblue-samba-exploitation-samba-victim
    networks:
      ctf-eternalblue-samba-exploitation-net:
        ipv4_address: 172.26.193.155
    restart: unless-stopped
  attacker-kali:
    build:
      context: ./attacker-kali
      dockerfile: Dockerfile
    container_name: ctf-eternalblue-samba-exploitation-attacker-kali
    networks:
      ctf-eternalblue-samba-exploitation-net:
        ipv4_address: 172.26.193.3
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
networks:
  ctf-eternalblue-samba-exploitation-net:
    name: ctf-eternalblue-samba-exploitation-net
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.26.193.0/24
          gateway: 172.26.193.1
