version: '3.8'

services:
  ctf-smb-misconfiguration-challenge-smb-server:
    build:
      context: ./smb-server
      dockerfile: Dockerfile
    container_name: ctf-smb-misconfiguration-challenge-smb-server
    hostname: smb-server
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "smb-misconfiguration-challenge"
    networks:
      ctf-smb-misconfiguration-challenge-net:
        ipv4_address: 172.23.200.22
    ports:
      - "445"
    stdin_open: true
    tty: true

  ctf-smb-misconfiguration-challenge-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-smb-misconfiguration-challenge-attacker
    hostname: attacker
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "smb-misconfiguration-challenge"
    networks:
      ctf-smb-misconfiguration-challenge-net:
        ipv4_address: 172.23.200.3
      ctf-instances-network:
    stdin_open: true
    tty: true

networks:
  ctf-smb-misconfiguration-challenge-net:
    driver: bridge
    ipam:
      config:
        - subnet: [object Object]
  ctf-instances-network:
    external: true
          gateway: 172.23.200.1
  ctf-instances-network:
    external: true
