services:
  fileserver:
    build:
      context: ./fileserver
      dockerfile: Dockerfile
    container_name: ctf-corporate-file-infiltration-fileserver
    networks:
      ctf-corporate-file-infiltration-net:
        ipv4_address: 172.24.193.184
    restart: unless-stopped
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: ctf-corporate-file-infiltration-attacker
    networks:
      ctf-corporate-file-infiltration-net:
        ipv4_address: 172.24.193.3
      ctf-instances-network: {}
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
networks:
  ctf-corporate-file-infiltration-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.193.0/24
          gateway: 172.24.193.1
  ctf-instances-network:
    external: true
