version: '3.8'

services:
  ctf-corporate-network-reconnaissance-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-corporate-network-reconnaissance-attacker
    hostname: attacker-workstation
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "corporate-network-reconnaissance"
    networks:
      ctf-corporate-network-reconnaissance-net:
        ipv4_address: 172.23.206.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-corporate-network-reconnaissance-corporate-web-server:
    build:
      context: ./corporate-web-server
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-reconnaissance-corporate-web-server
    hostname: corporate-web-server
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-reconnaissance"
    networks:
      ctf-corporate-network-reconnaissance-net:
        ipv4_address: 172.23.206.178
    ports:
      - "80"
      - "443"
      - "22"
    stdin_open: true
    tty: true

  ctf-corporate-network-reconnaissance-file-storage-server:
    build:
      context: ./file-storage-server
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-reconnaissance-file-storage-server
    hostname: file-storage-server
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-reconnaissance"
    networks:
      ctf-corporate-network-reconnaissance-net:
        ipv4_address: 172.23.206.11
    ports:
      - "21"
      - "445"
      - "22"
    stdin_open: true
    tty: true

  ctf-corporate-network-reconnaissance-legacy-terminal-server:
    build:
      context: ./legacy-terminal-server
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-reconnaissance-legacy-terminal-server
    hostname: legacy-terminal-server
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-reconnaissance"
    networks:
      ctf-corporate-network-reconnaissance-net:
        ipv4_address: 172.23.206.12
    ports:
      - "22"
    stdin_open: true
    tty: true

networks:
  ctf-corporate-network-reconnaissance-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.206.0/24
          gateway: 172.23.206.1
  ctf-instances-network:
    external: true
