version: '3.8'

services:
  ctf-corporate-network-reconnaissance-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-corporate-network-reconnaissance-attacker
    hostname: attacker-workstation
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "corporate-network-reconnaissance"
    networks:
      ctf-corporate-network-reconnaissance-net:
        ipv4_address: 172.23.201.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-corporate-network-reconnaissance-corporate-server:
    build:
      context: ./corporate-server
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-reconnaissance-corporate-server
    hostname: corporate-server
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-reconnaissance"
    networks:
      ctf-corporate-network-reconnaissance-net:
        ipv4_address: 172.23.201.135
    ports:
      - "22"
      - "21"
      - "80"
    stdin_open: true
    tty: true

  ctf-corporate-network-reconnaissance-backup-nas:
    build:
      context: ./backup-nas
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-reconnaissance-backup-nas
    hostname: backup-nas
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-reconnaissance"
    networks:
      ctf-corporate-network-reconnaissance-net:
        ipv4_address: 172.23.201.11
    ports:
      - "445"
      - "22"
    stdin_open: true
    tty: true

networks:
  ctf-corporate-network-reconnaissance-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.201.0/24
          gateway: 172.23.201.1
  ctf-instances-network:
    external: true
