services:
  crypto-server:
    build:
      context: ./crypto-server
      dockerfile: Dockerfile
    container_name: ctf-corporate-cipher-breach-crypto-server
    networks:
      ctf-corporate-cipher-breach-net:
        ipv4_address: 172.30.193.104
    restart: unless-stopped
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: ctf-corporate-cipher-breach-attacker
    networks:
      ctf-corporate-cipher-breach-net:
        ipv4_address: 172.30.193.3
      ctf-instances-network: {}
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
networks:
  ctf-corporate-cipher-breach-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.193.0/24
          gateway: 172.30.193.1
  ctf-instances-network:
    external: true
