version: '3.8'

services:
  ctf-corporate-network-infiltration-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-corporate-network-infiltration-attacker
    hostname: attacker-machine
    networks:
      ctf-corporate-network-infiltration-net:
        ipv4_address: 172.27.193.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-corporate-network-infiltration-ftp-server:
    build:
      context: ./ftp-server
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-infiltration-ftp-server
    hostname: ftp-server
    networks:
      ctf-corporate-network-infiltration-net:
        ipv4_address: 172.27.193.10
    ports:
      - "21"
      - "22"
    stdin_open: true
    tty: true

  ctf-corporate-network-infiltration-internal-victim:
    build:
      context: ./internal-victim
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-infiltration-internal-victim
    hostname: internal-victim
    networks:
      ctf-corporate-network-infiltration-net:
        ipv4_address: 172.27.193.11
    ports:
      - "22"
      - "80"
    stdin_open: true
    tty: true

networks:
  ctf-corporate-network-infiltration-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.193.0/24
          gateway: 172.27.193.1
  ctf-instances-network:
    external: true
