version: '3.8'

services:
  ctf-corporate-network-infiltration-attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-corporate-network-infiltration-attacker
    hostname: attacker-workstation
    labels:
      com.ctf.machine.type: "attacker"
      com.ctf.challenge: "corporate-network-infiltration"
    networks:
      ctf-corporate-network-infiltration-net:
        ipv4_address: 172.27.193.3
      ctf-instances-network:
    stdin_open: true
    tty: true

  ctf-corporate-network-infiltration-corporate-fileserver:
    build:
      context: ./corporate-fileserver
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-infiltration-corporate-fileserver
    hostname: corporate-fileserver
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-infiltration"
    networks:
      ctf-corporate-network-infiltration-net:
        ipv4_address: 172.27.193.36
    ports:
      - "21"
      - "22"
    stdin_open: true
    tty: true

  ctf-corporate-network-infiltration-hr-department:
    build:
      context: ./hr-department
      dockerfile: Dockerfile
    container_name: ctf-corporate-network-infiltration-hr-department
    hostname: hr-department
    labels:
      com.ctf.machine.type: "victim"
      com.ctf.challenge: "corporate-network-infiltration"
    networks:
      ctf-corporate-network-infiltration-net:
        ipv4_address: 172.27.193.11
    ports:
      - "445"
      - "22"
    stdin_open: true
    tty: true

networks:
  ctf-corporate-network-infiltration-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.193.0/24
          gateway: 172.27.193.1
  ctf-instances-network:
    external: true
