version: '3.8'
services:
  victim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ctf-multi-vulnerability-exploitation-victim
    hostname: victim
    networks:
      ctf-network:
        ipv4_address: 172.23.202.10
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: ctf-multi-vulnerability-exploitation-attacker
    hostname: attacker
    networks:
      ctf-network:
        ipv4_address: 172.23.202.3
      ctf-instances-network: {}
networks:
  ctf-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.202.0/24
          gateway: 172.23.202.1
  ctf-instances-network:
    external: true
    name: ctf-instances-network
