version: '3.8'
services:
  ftpserver:
    build:
      context: ./ftpserver
      dockerfile: Dockerfile
    container_name: ctf-ftp-hidden-flag-victim
    hostname: victim
    ports:
      - "2121:21"
      - "30000-30009:30000-30009"
    networks:
      - ctf-network
    volumes:
      - ./ftpserver/data:/home/ftp
  attacker:
    image: kasmweb/kali-rolling-desktop:1.15.0
    container_name: ctf-ftp-hidden-flag-attacker
    hostname: attacker
    ports:
      - "6901:6901"
    networks:
      - ctf-network
    shm_size: "512m"
    environment:
      - VNC_PW=password
      - KASM_PORT=6901
networks:
  ctf-network:
    driver: bridge
