version: '3.8'
services:
  victim:
    build:
      context: ./ftp
      dockerfile: Dockerfile
    container_name: ctf-ftp-access-misconfiguration-victim
    hostname: victim
    ports:
      - "21:21"
      - "3000-3001:3000-3001"
      - "8080:8080"
    networks:
      - ctf-network
  attacker:
    image: kasmweb/kali-rolling-desktop:1.15.0
    container_name: ctf-ftp-access-misconfiguration-attacker
    hostname: attacker
    ports:
      - "6901:6901"
    networks:
      - ctf-network
    shm_size: "512m"
    environment:
      - VNC_PW=password
      - KASM_PORT=6901
networks:
  ctf-network:
    driver: bridge