services:
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: ctf-network-reconnaissance-multi-target-infiltration-attacker
    networks:
      ctf-network-reconnaissance-multi-target-infiltration-net:
        ipv4_address: 172.26.145.3
    cap_add:
      - NET_RAW
      - NET_ADMIN
    stdin_open: true
    tty: true
    restart: unless-stopped
  victim1:
    build:
      context: ./victim1
      dockerfile: Dockerfile
    container_name: ctf-network-reconnaissance-multi-target-infiltration-victim1
    networks:
      ctf-network-reconnaissance-multi-target-infiltration-net:
        ipv4_address: 172.26.145.95
    restart: unless-stopped
  victim2:
    build:
      context: ./victim2
      dockerfile: Dockerfile
    container_name: ctf-network-reconnaissance-multi-target-infiltration-victim2
    networks:
      ctf-network-reconnaissance-multi-target-infiltration-net:
        ipv4_address: 172.26.145.125
    restart: unless-stopped
  victim3:
    build:
      context: ./victim3
      dockerfile: Dockerfile
    container_name: ctf-network-reconnaissance-multi-target-infiltration-victim3
    networks:
      ctf-network-reconnaissance-multi-target-infiltration-net:
        ipv4_address: 172.26.145.70
    restart: unless-stopped
  victim4:
    build:
      context: ./victim4
      dockerfile: Dockerfile
    container_name: ctf-network-reconnaissance-multi-target-infiltration-victim4
    networks:
      ctf-network-reconnaissance-multi-target-infiltration-net:
        ipv4_address: 172.26.145.46
    restart: unless-stopped
networks:
  ctf-network-reconnaissance-multi-target-infiltration-net:
    name: ctf-network-reconnaissance-multi-target-infiltration-net
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.26.145.0/24
          gateway: 172.26.145.1
